<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;800&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Kanit:wght@400;600;700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@500&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Icons:wght@400&display=swap" />
    <style>
        :root {
        --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
            "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
            "Source Han Sans CN", sans-serif;
        }

        .main-container {
        overflow: hidden;
        }

        .main-container,
        .main-container * {
        box-sizing: border-box;
        }

        input,
        select,
        textarea,
        button {
        outline: 0;
        }

        .main-container {
        position: relative;
        width: 1440px;
        height: 1146px;
        margin: 0 auto;
        }
        .rectangle {
        position: absolute;
        width: 1440px;
        height: 1213px;
        top: 0;
        left: 0;
        background: #ffffff;
        }
        .rectangle-1 {
        position: relative;
        width: 1440px;
        height: 130px;
        margin: -1px 0 0 0;
        background: #000000;
        z-index: 3;
        box-shadow: 0 6px 4px 0 rgba(0, 0, 0, 0.25);
        }
        .logo-putih {
        position: absolute;
        width: 103px;
        height: 40px;
        top: 34px;
        left: 36px;
        background: url(./assets/images/61990e8a-d4e2-4cad-9aa3-649eae3e0364.png)
            no-repeat center;
        background-size: cover;
        z-index: 5;
        }
        .penjadwalan-pelayanan {
        display: flex;
        align-items: flex-start;
        justify-content: center;
        position: absolute;
        width: 124px;
        height: 44px;
        top: 45px;
        left: 909px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: center;
        text-overflow: initial;
        z-index: 7;
        overflow: hidden;
        }
        .daftar-pelayanan {
        display: flex;
        align-items: flex-start;
        justify-content: center;
        position: absolute;
        width: 96px;
        height: 44px;
        top: 49px;
        left: 409px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: center;
        text-overflow: initial;
        z-index: 15;
        overflow: hidden;
        }
        .list-jemaat {
        display: flex;
        align-items: flex-start;
        justify-content: center;
        position: absolute;
        width: 69px;
        height: 44px;
        top: 49px;
        left: 1086px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: center;
        text-overflow: initial;
        z-index: 9;
        overflow: hidden;
        }
        .komsel {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 53px;
        left: 558px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: left;
        white-space: nowrap;
        z-index: 11;
        }
        .bareng {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 53px;
        left: 682px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: left;
        white-space: nowrap;
        z-index: 12;
        }
        .event {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 53px;
        left: 803px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: left;
        white-space: nowrap;
        z-index: 13;
        }
        .home {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 54px;
        left: 299px;
        color: #eeb120;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 800;
        line-height: 21.942px;
        text-align: left;
        white-space: nowrap;
        z-index: 14;
        }
        .analisis {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 58px;
        left: 1208px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 21.942px;
        text-align: left;
        white-space: nowrap;
        z-index: 8;
        }
        .best-church {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 77px;
        left: 36px;
        color: #f4f4f4;
        font-family: Montserrat, var(--default-font-family);
        font-size: 15px;
        font-weight: 400;
        line-height: 18.285px;
        text-align: left;
        white-space: nowrap;
        z-index: 4;
        }
        .line {
        position: absolute;
        width: 95.016px;
        height: 3px;
        top: 86px;
        left: 285px;
        background: url(./assets/images/a87e043e-c146-4015-b500-9307be498680.png)
            no-repeat center;
        background-size: cover;
        z-index: 16;
        }
        .rectangle-2 {
        position: relative;
        width: 1205px;
        height: 296px;
        margin: 173px 0 0 117px;
        background: #f3f3f3;
        z-index: 25;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        }
        .rectangle-3 {
        position: absolute;
        width: 194px;
        height: 51px;
        top: 17px;
        left: 1011px;
        cursor: pointer;
        background: #eeb120;
        border: none;
        z-index: 37;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        }
        .jemaat-mendaftar {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        width: 90px;
        height: 44px;
        top: 4px;
        left: 59px;
        color: #ffffff;
        font-family: DM Sans, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        text-overflow: initial;
        z-index: 46;
        overflow: hidden;
        }
        .rectangle-4 {
        position: absolute;
        width: 50px;
        height: 44px;
        top: 4px;
        left: 3px;
        background: #ffffff;
        z-index: 39;
        }
        .number-15 {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 28px;
        top: 8px;
        left: 11px;
        color: #000000;
        font-family: Roboto, var(--default-font-family);
        font-size: 24px;
        font-weight: 700;
        line-height: 28px;
        text-align: left;
        white-space: nowrap;
        z-index: 45;
        }
        .right {
        position: absolute;
        width: 20px;
        height: 20px;
        top: 16px;
        left: 161px;
        z-index: 50;
        overflow: hidden;
        }
        .safe-area {
        position: relative;
        width: 16.667px;
        height: 16.667px;
        margin: 1.667px 0 0 1.667px;
        z-index: 51;
        overflow: visible auto;
        }
        .vector {
        position: relative;
        width: 16.5px;
        height: 13.167px;
        margin: 1.75px 0 0 0.08px;
        background: url(./assets/images/9852889b-508c-4992-b81f-7125cf3fcdcb.png)
            no-repeat center;
        background-size: 100% 100%;
        z-index: 52;
        }
        .rectangle-5 {
        position: absolute;
        width: 155px;
        height: 51px;
        top: 17px;
        left: 419px;
        background: #000000;
        z-index: 44;
        }
        .archieved {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 16px;
        left: 53px;
        color: #ffffff;
        font-family: DM Sans, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        white-space: nowrap;
        z-index: 49;
        }
        .button-rectangle {
        position: absolute;
        width: 110px;
        height: 51px;
        top: 17px;
        left: 890px;
        cursor: pointer;
        background: #000000;
        border: none;
        z-index: 40;
        }
        .mode-edit {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        width: 35px;
        height: 22px;
        top: 14px;
        left: 14px;
        color: #ffffff;
        font-family: Material Icons, var(--default-font-family);
        font-size: 35px;
        font-weight: 400;
        line-height: 22px;
        text-align: center;
        white-space: nowrap;
        z-index: 47;
        }
        .edit {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 15px;
        left: 59px;
        color: #ffffff;
        font-family: DM Sans, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        white-space: nowrap;
        z-index: 48;
        }
        .rectangle-6 {
        position: absolute;
        width: 58px;
        height: 51px;
        top: 17px;
        left: 821px;
        background: #000000;
        z-index: 42;
        }
        .n {
        position: absolute;
        width: 340px;
        height: 242px;
        top: 38px;
        left: 38px;
        background: url(./assets/images/99529d84e7724fe0aa9e5539d4c83ecf05e8bd83.png)
            no-repeat center;
        background-size: cover;
        z-index: 29;
        }
        .rectangle-7 {
        position: relative;
        width: 100px;
        height: 60px;
        margin: 182px 0 0 240px;
        font-size: 0px;
        background: rgba(0, 0, 0, 0.25);
        z-index: 32;
        overflow: visible auto;
        }
        .mar {
        display: block;
        position: relative;
        height: 19px;
        margin: 7px 0 0 32px;
        color: #f4f4f4;
        font-family: Roboto, var(--default-font-family);
        font-size: 16px;
        font-weight: 900;
        line-height: 18.75px;
        text-align: left;
        white-space: nowrap;
        letter-spacing: 1.6px;
        z-index: 33;
        }
        .number-30 {
        display: block;
        position: relative;
        height: 38px;
        margin: -5px 0 0 31px;
        color: #f4f4f4;
        font-family: Roboto, var(--default-font-family);
        font-size: 32px;
        font-weight: 900;
        line-height: 37.5px;
        text-align: left;
        white-space: nowrap;
        letter-spacing: 3.2px;
        z-index: 34;
        }
        .putus-atau-terus {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 54px;
        top: 81px;
        left: 419px;
        color: #000000;
        font-family: Kanit, var(--default-font-family);
        font-size: 36px;
        font-weight: 600;
        line-height: 53.82px;
        text-align: left;
        white-space: nowrap;
        z-index: 28;
        }
        .line-8 {
        position: absolute;
        width: 982px;
        height: 2px;
        top: 85px;
        left: 223px;
        background: url(./assets/images/48e5cb63-d5d0-4f06-8f18-ecd8fca73f79.png)
            no-repeat center;
        background-size: cover;
        z-index: 27;
        }
        .ciputra-world-mall {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 23px;
        top: 133px;
        left: 419px;
        color: #646464;
        font-family: Roboto, var(--default-font-family);
        font-size: 20px;
        font-weight: 700;
        line-height: 23px;
        text-align: left;
        white-space: nowrap;
        z-index: 30;
        }
        .yess-surabaya-valentines-day {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        width: 572px;
        height: 97px;
        top: 170px;
        left: 419px;
        color: #646464;
        font-family: Roboto, var(--default-font-family);
        font-size: 20px;
        font-weight: 400;
        line-height: 23.438px;
        text-align: left;
        letter-spacing: 0.4px;
        z-index: 31;
        }
        .rectangle-9 {
        position: relative;
        width: 1205px;
        height: 296px;
        margin: 41px 0 0 117px;
        background: #f3f3f3;
        z-index: 55;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        }
        .rectangle-a {
        position: absolute;
        width: 194px;
        height: 51px;
        top: 18px;
        left: 1011px;
        cursor: pointer;
        background: #eeb120;
        border: none;
        z-index: 66;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        }
        .jemaat-mendaftar-b {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        width: 90px;
        height: 44px;
        top: 4px;
        left: 59px;
        color: #ffffff;
        font-family: DM Sans, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        text-overflow: initial;
        z-index: 70;
        overflow: hidden;
        }
        .rectangle-c {
        position: absolute;
        width: 50px;
        height: 44px;
        top: 4px;
        left: 3px;
        background: #ffffff;
        z-index: 67;
        }
        .empty {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 28px;
        top: 8px;
        left: 11px;
        color: #000000;
        font-family: Roboto, var(--default-font-family);
        font-size: 24px;
        font-weight: 700;
        line-height: 28px;
        text-align: left;
        white-space: nowrap;
        z-index: 69;
        }
        .right-d {
        position: absolute;
        width: 20px;
        height: 20px;
        top: 19px;
        left: 162px;
        z-index: 73;
        overflow: hidden;
        }
        .safearea {
        position: relative;
        width: 16.667px;
        height: 16.667px;
        margin: 1.667px 0 0 1.667px;
        z-index: 74;
        overflow: visible auto;
        }
        .vector-e {
        position: relative;
        width: 16.5px;
        height: 13.167px;
        margin: 1.75px 0 0 0.08px;
        background: url(./assets/images/672c3efe-9e5a-4374-ba15-7b8ddf0d09fa.png)
            no-repeat center;
        background-size: 100% 100%;
        z-index: 75;
        }
        .rectangle-f {
        position: absolute;
        width: 155px;
        height: 51px;
        top: 18px;
        left: 433px;
        background: #000000;
        z-index: 81;
        }
        .archive {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        width: 32px;
        height: 32px;
        top: 10px;
        left: 12px;
        color: #ffffff;
        font-family: Material Icons, var(--default-font-family);
        font-size: 32px;
        font-weight: 400;
        line-height: 32px;
        text-align: center;
        white-space: nowrap;
        z-index: 83;
        }
        .archieved-10 {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 15px;
        left: 53px;
        color: #ffffff;
        font-family: DM Sans, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        white-space: nowrap;
        z-index: 82;
        }
        .rectangle-11 {
        position: absolute;
        width: 102px;
        height: 51px;
        top: 18px;
        left: 897px;
        background: #000000;
        z-index: 68;
        }
        .edit-12 {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 15px;
        left: 51px;
        color: #ffffff;
        font-family: DM Sans, var(--default-font-family);
        font-size: 18px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        white-space: nowrap;
        z-index: 72;
        }
        .mode-edit-13 {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        width: 24px;
        height: 22px;
        top: 15px;
        left: 15px;
        color: #ffffff;
        font-family: Material Icons, var(--default-font-family);
        font-size: 24px;
        font-weight: 400;
        line-height: 22px;
        text-align: center;
        white-space: nowrap;
        z-index: 71;
        }
        .rectangle-14 {
        position: absolute;
        width: 58px;
        height: 51px;
        top: 18px;
        left: 821px;
        background: #000000;
        z-index: 77;
        }
        .delete {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        width: 32px;
        height: 32px;
        top: 10px;
        left: 14px;
        color: #ffffff;
        font-family: Material Icons, var(--default-font-family);
        font-size: 32px;
        font-weight: 400;
        line-height: 32px;
        text-align: center;
        white-space: nowrap;
        z-index: 79;
        }
        .rectangle-15 {
        position: absolute;
        width: 340px;
        height: 242px;
        top: 27px;
        left: 49px;
        background: url(./assets/images/50a3f1c3-272a-4d73-88c8-07cfbe08ac34.png)
            no-repeat center;
        background-size: cover;
        z-index: 57;
        }
        .rectangle-16 {
        position: relative;
        width: 100px;
        height: 60px;
        margin: 182px 0 0 240px;
        font-size: 0px;
        background: rgba(0, 0, 0, 0.25);
        z-index: 61;
        overflow: visible auto;
        }
        .apr {
        display: block;
        position: relative;
        height: 19px;
        margin: 7px 0 0 32px;
        color: #f4f4f4;
        font-family: Roboto, var(--default-font-family);
        font-size: 16px;
        font-weight: 900;
        line-height: 18.75px;
        text-align: left;
        white-space: nowrap;
        letter-spacing: 1.6px;
        z-index: 62;
        }
        .text-1c {
        display: block;
        position: relative;
        height: 38px;
        margin: -5px 0 0 6px;
        color: #f4f4f4;
        font-family: Roboto, var(--default-font-family);
        font-size: 32px;
        font-weight: 900;
        line-height: 37.5px;
        text-align: left;
        white-space: nowrap;
        z-index: 63;
        }
        .yess-leardership-mission-training-vii {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 54px;
        top: 86px;
        left: 430px;
        color: #000000;
        font-family: Kanit, var(--default-font-family);
        font-size: 36px;
        font-weight: 600;
        line-height: 53.82px;
        text-align: left;
        white-space: nowrap;
        z-index: 64;
        }
        .line-17 {
        position: absolute;
        width: 982px;
        height: 2px;
        top: 87px;
        left: 223px;
        background: url(./assets/images/0f15f02d-9d5f-4d98-9266-73b07f3cc912.png)
            no-repeat center;
        background-size: cover;
        z-index: 38;
        }
        .line-18 {
        position: absolute;
        width: 982px;
        height: 2px;
        top: 87px;
        left: 208px;
        background: url(./assets/images/a3b070fa-8196-4ff5-acbc-a6e685aeaadf.png)
            no-repeat center;
        background-size: cover;
        z-index: 56;
        }
        .desa-birkium-soe-nusa-tenggara-timur {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 23px;
        top: 139px;
        left: 430px;
        color: #646464;
        font-family: Roboto, var(--default-font-family);
        font-size: 20px;
        font-weight: 700;
        line-height: 23px;
        text-align: left;
        white-space: nowrap;
        z-index: 59;
        }
        .biarlah-semangat-misi-terus-menyala {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        width: 572px;
        height: 79px;
        top: 183px;
        left: 430px;
        color: #646464;
        font-family: Roboto, var(--default-font-family);
        font-size: 20px;
        font-weight: 400;
        line-height: 23.438px;
        text-align: left;
        text-overflow: initial;
        letter-spacing: 0.4px;
        z-index: 60;
        overflow: hidden;
        }
        .event-19 {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 120px;
        top: 156px;
        left: 81px;
        color: #000000;
        font-family: Kanit, var(--default-font-family);
        font-size: 80px;
        font-weight: 700;
        line-height: 119.6px;
        text-align: left;
        white-space: nowrap;
        z-index: 84;
        }
        .rectangle-1a {
        position: absolute;
        width: 336px;
        height: 98px;
        top: 169px;
        left: 50%;
        cursor: pointer;
        background: #000000;
        border: none;
        transform: translate(80.36%, 0);
        z-index: 88;
        border-radius: 25px;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        }
        .add-circle-outline {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        width: 60px;
        height: 60px;
        top: 17px;
        left: 44px;
        color: #eeb120;
        font-family: Material Icons, var(--default-font-family);
        font-size: 60px;
        font-weight: 400;
        line-height: 60px;
        text-align: center;
        white-space: nowrap;
        z-index: 90;
        }
        .add-event {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 57px;
        top: 18px;
        left: 120px;
        color: #eeb120;
        font-family: Kanit, var(--default-font-family);
        font-size: 38px;
        font-weight: 400;
        line-height: 56.81px;
        text-align: left;
        white-space: nowrap;
        z-index: 89;
        }
        .rectangle-1b {
        position: absolute;
        width: 203px;
        height: 50px;
        top: 194px;
        left: 333px;
        cursor: pointer;
        background: #eeb120;
        border: none;
        z-index: 85;
        border-radius: 20px;
        }
        .keyboard-arrow-up {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        width: 36px;
        height: 36px;
        top: 7px;
        left: 146px;
        color: #000000;
        font-family: Material Icons, var(--default-font-family);
        font-size: 36px;
        font-weight: 400;
        line-height: 36px;
        text-align: center;
        white-space: nowrap;
        transform: rotate(-180deg);
        z-index: 86;
        }
        .berlangsung {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        height: 22px;
        top: 13px;
        left: 27px;
        color: #000000;
        font-family: DM Sans, var(--default-font-family);
        font-size: 20px;
        font-weight: 500;
        line-height: 22px;
        text-align: left;
        white-space: nowrap;
        z-index: 87;
        }
        .line-1c {
        position: absolute;
        width: 10px;
        height: 641px;
        top: 697px;
        left: 947px;
        background: url(./assets/images/b83ebe53-a115-412f-b87a-baa62718ff2c.png)
            no-repeat center;
        background-size: cover;
        z-index: 92;
        }
        .line-1d {
        position: absolute;
        width: 543.745px;
        height: 381.218px;
        top: 696.782px;
        left: 1066px;
        background: url(./assets/images/5f86fb6b-c4be-4eeb-966d-9cc2d562f917.png)
            no-repeat center;
        background-size: cover;
        z-index: 91;
        }
        .rectangle-1e {
        position: absolute;
        width: 1440px;
        height: 142px;
        top: 1078px;
        left: 0;
        background: #000000;
        z-index: 18;
        border-radius: 40px 40px 0 0;
        }
        .image {
        position: absolute;
        width: 70px;
        height: 70px;
        top: 38px;
        left: 50px;
        background: url(./assets/images/9901ff329f073d0704c58e121a346740de16b8e8.png)
            no-repeat center;
        background-size: cover;
        z-index: 21;
        }
        .image-1f {
        position: absolute;
        width: 70px;
        height: 70px;
        top: 38px;
        left: 150px;
        background: url(./assets/images/73aef9e0ed5ef1ed108a123e9a54cf2e52e4a4d9.png)
            no-repeat center;
        background-size: cover;
        z-index: 22;
        }
        .image-20 {
        position: absolute;
        width: 70px;
        height: 70px;
        top: 38px;
        left: 250px;
        background: url(./assets/images/76f9b2354c0e31cc1f2dea6fc755bc26d8c1bc54.png)
            no-repeat center;
        background-size: cover;
        z-index: 23;
        }
        .image-21 {
        position: absolute;
        width: 66px;
        height: 66px;
        top: 38px;
        left: 1321px;
        background: url(./assets/images/ddc96dc25eb3a571eb74851b4f9a9f3062acd5b4.png)
            no-repeat center;
        background-size: cover;
        z-index: 19;
        }
        .contact-us {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        position: absolute;
        width: 243px;
        height: 85px;
        top: 50px;
        left: 1144px;
        color: #ffffff;
        font-family: Roboto, var(--default-font-family);
        font-size: 32px;
        font-weight: 500;
        line-height: 45px;
        text-align: left;
        z-index: 20;
        }
    </style>
  </head>
  <body>
    <div class="main-container">
      <div class="rectangle">
        <div class="rectangle-1">
          <div class="logo-putih"></div>
          <span class="penjadwalan-pelayanan">Penjadwalan <br />Pelayanan</span
          ><span class="daftar-pelayanan">Daftar<br />Pelayanan</span
          ><span class="list-jemaat">List<br />Jemaat</span
          ><span class="komsel">KomSel</span><span class="bareng">Bareng</span
          ><span class="event">Event</span><span class="home">Home</span
          ><span class="analisis">Analisis</span
          ><span class="best-church">BEST CHURCH</span>
          <div class="line"></div>
        </div>
        <div class="rectangle-2">
          <button class="rectangle-3">
            <span class="jemaat-mendaftar">Jemaat <br />mendaftar</span>
            <div class="rectangle-4"><span class="number-15">15</span></div>
            <div class="right">
              <div class="safe-area"><div class="vector"></div></div>
            </div>
          </button>
          <div class="rectangle-5">
            <span class="archieved">Archieved</span>
          </div>
          <button class="button-rectangle">
            <span class="mode-edit">mode_edit</span
            ><span class="edit">Edit</span>
          </button>
          <div class="rectangle-6"></div>
          <div class="n">
            <div class="rectangle-7">
              <span class="mar">MAR</span><span class="number-30">30</span>
            </div>
          </div>
          <span class="putus-atau-terus">Putus atau Terus</span>
          <div class="line-8"></div>
          <span class="ciputra-world-mall"
            >Ciputra World Mall 2nd floor | 30 Maret 2024 | 16.30 WIB</span
          ><span class="yess-surabaya-valentines-day"
            >YESS Surabaya Valentine's Day Celebration “Putus atau Terus”<br />Ini
            adalah kesempatan untuk terinspirasi sebagai pasangan! juga
            merupakan PENGALAMAN YANG HEBAT bagi kamu ya...</span
          >
        </div>
        <div class="rectangle-9">
          <button class="rectangle-a">
            <span class="jemaat-mendaftar-b">Jemaat <br />mendaftar</span>
            <div class="rectangle-c"><span class="empty">20</span></div>
            <div class="right-d">
              <div class="safearea"><div class="vector-e"></div></div>
            </div>
          </button>
          <div class="rectangle-f">
            <span class="archive">archive</span
            ><span class="archieved-10">Archieved</span>
          </div>
          <div class="rectangle-11">
            <span class="edit-12">Edit</span
            ><span class="mode-edit-13">mode_edit</span>
          </div>
          <div class="rectangle-14"><span class="delete">delete</span></div>
          <div class="rectangle-15">
            <div class="rectangle-16">
              <span class="apr">APR</span><span class="text-1c">19-21</span>
            </div>
          </div>
          <span class="yess-leardership-mission-training-vii"
            >YESS Leardership Mission Training VII</span
          >
          <div class="line-17"></div>
          <div class="line-18"></div>
          <span class="desa-birkium-soe-nusa-tenggara-timur"
            >Desa Birkium, Soe, Nusa Tenggara Timur | 19-21 April 2024</span
          ><span class="biarlah-semangat-misi-terus-menyala"
            >Biarlah semangat misi terus menyala dalam hidup kita.<br />Uis Neno
            nokan kit, Immanuel!<br />Sampe ketemu di YLMT, basodara dong!</span
          >
        </div>
        <span class="event-19">Event</span
        ><button class="rectangle-1a">
          <span class="add-circle-outline">add_circle_outline</span
          ><span class="add-event">Add Event</span></button
        ><button class="rectangle-1b">
          <span class="keyboard-arrow-up">keyboard_arrow_up</span
          ><span class="berlangsung">Berlangsung</span>
        </button>
      </div>
      <div class="line-1c"></div>
      <div class="line-1d"></div>
      <div class="rectangle-1e">
        <div class="image"></div>
        <div class="image-1f"></div>
        <div class="image-20"></div>
        <div class="image-21"></div>
        <span class="contact-us">Contact Us</span>
      </div>
    </div>
  </body>
</html>

<!-- Delete Confirmation
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div class="main-container">
      <div class="background">
        <span class="delete-event-message"
          >Anda yakin akan menghapus Event <br />“YESS Leardership Mission
          Training VII”</span
        >
        <div class="flex-row-ff">
          <div class="rectangle"><span class="cancel-button">CANCEL</span></div>
          <div class="button">
            <button class="button-background"></button>
            <div class="button-shadow"></div>
            <span class="delete-button">DELETE</span>
          </div>
        </div>
      </div>
    </div>
  </body>
</html> -->

<!-- :root {
  --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
    "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
    "Source Han Sans CN", sans-serif;
}

.main-container {
  overflow: hidden;
}

.main-container,
.main-container * {
  box-sizing: border-box;
}

input,
select,
textarea,
button {
  outline: 0;
}

.main-container {
  position: relative;
  width: 631px;
  height: 578px;
  margin: 0 auto;
  overflow: hidden auto;
}
.background {
  position: relative;
  width: 631px;
  height: 239px;
  margin: 0 0 0 0;
  font-size: 0px;
  background: #ffffff;
  overflow: visible auto;
}
.delete-event-message {
  display: flex;
  align-items: flex-start;
  justify-content: center;
  position: relative;
  width: 571px;
  height: 56px;
  margin: 54px 0 0 30px;
  color: #000000;
  font-family: Roboto, var(--default-font-family);
  font-size: 24px;
  font-weight: 700;
  line-height: 28.125px;
  text-align: center;
  z-index: 9;
}
.flex-row-ff {
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: relative;
  width: 266.176px;
  height: 56px;
  margin: 27px 0 0 171px;
  z-index: 7;
}
.rectangle {
  flex-shrink: 0;
  position: relative;
  width: 134px;
  height: 56px;
  background: #e5e5e5;
  border: 1px solid #000000;
  z-index: 7;
}
.cancel-button {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 24px;
  top: 15px;
  left: 22px;
  color: #000000;
  font-family: DM Sans, var(--default-font-family);
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 1.6px;
  z-index: 8;
}
.button {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: nowrap;
  flex-shrink: 0;
  gap: 8px;
  position: relative;
  width: 84.176px;
  padding: 16px 24px 16px 24px;
  z-index: 2;
  border-radius: 40px;
}
.button-background {
  flex-shrink: 0;
  position: absolute;
  width: 134px;
  height: 56px;
  top: 50%;
  left: 50%;
  cursor: pointer;
  background: #000000;
  border: none;
  transform: translate(-50.07%, -50%);
  z-index: 4;
}
.button-shadow {
  flex-shrink: 0;
  position: absolute;
  top: 0;
  right: 0.18px;
  bottom: 0;
  left: 0;
  background: #000000;
  z-index: 3;
}
.delete-button {
  flex-shrink: 0;
  flex-basis: auto;
  position: relative;
  height: 24px;
  color: #ffffff;
  font-family: DM Sans, var(--default-font-family);
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 2px;
  z-index: 5;
} -->

<!-- Jemaat mendaftar
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Kanit:wght@400&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div class="main-container">
      <button class="button-group">
        <div class="group-section">
          <span class="back-button">KEMBALI</span>
          <div class="background"></div>
        </div>
      </button>
      <div class="rectangle"></div>
      <div class="rectangle-1"></div>
      <span class="registration-event"
        >PENDAFTARAN EVENT > Putus atau Terus</span
      >
      <div class="line"></div>
      <div class="rectangle-2"></div>
      <div class="rectangle-3"></div>
      <button class="button"></button
      ><button class="daftar-nama-jemaat">
        Daftar nama jemaat yang sudah mendaftar</button
      ><span class="number">5</span><span class="jumlah">Jumlah</span>
      <div class="rectangle-4"></div>
      <div class="rectangle-5"></div>
      <div class="line-6"></div>
      <div class="rectangle-7"></div>
      <span class="jackson-wang">Jackson Wang</span>
      <div class="rectangle-8"></div>
      <span class="jackson-wang-9">Jackson Wang</span
      ><span class="multimedia">Multimedia</span>
      <div class="rectangle-a"></div>
      <span class="jackson-wang-b">Jackson Wang</span>
      <div class="rectangle-c"></div>
      <span class="jackson-wang-d">Jackson Wang</span>
    </div>
  </body>
</html> -->

<!-- :root {
  --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
    "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
    "Source Han Sans CN", sans-serif;
}

.main-container {
  overflow: hidden;
}

.main-container,
.main-container * {
  box-sizing: border-box;
}

input,
select,
textarea,
button {
  outline: 0;
}

.main-container {
  position: relative;
  width: 1108px;
  height: 607px;
  margin: 0 auto;
}
.button-group {
  position: relative;
  width: 308px;
  height: 60px;
  margin: 517px 0 0 400px;
  cursor: pointer;
  background: transparent;
  border: none;
  z-index: 22;
}
.group-section {
  position: absolute;
  width: 308px;
  height: 60px;
  top: 0;
  left: 0;
  font-size: 0px;
  z-index: 23;
}
.back-button {
  display: block;
  position: relative;
  height: 24px;
  margin: 18px 0 0 105px;
  color: #ffffff;
  font-family: DM Sans, var(--default-font-family);
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 2px;
  z-index: 25;
}
.background {
  position: absolute;
  width: 308px;
  height: 60px;
  top: 50%;
  left: 50%;
  background: #eeb120;
  transform: translate(-50%, -50%);
  z-index: 24;
}
.rectangle {
  position: absolute;
  width: 1108px;
  height: 607px;
  top: 0;
  left: 0;
  background: #ffffff;
}
.rectangle-1 {
  position: absolute;
  width: 1108px;
  height: 78px;
  top: 0;
  left: 0;
  background: #f3f3f3;
  z-index: 9;
}
.registration-event {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 20px;
  left: 60px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 20;
}
.line {
  position: absolute;
  width: 1108.006px;
  height: 7px;
  top: 71px;
  left: -0.01px;
  background: url(./assets/images/2442b8c6-e80b-4e7e-9754-ca21c4d75085.png)
    no-repeat center;
  background-size: cover;
  z-index: 21;
}
.rectangle-2 {
  position: absolute;
  width: 1004px;
  height: 376px;
  top: 115px;
  left: 50%;
  background: #000000;
  transform: translate(-50%, 0);
  z-index: 2;
}
.rectangle-3 {
  position: absolute;
  width: 192px;
  height: 59px;
  top: 125px;
  left: 820px;
  background: #ffffff;
  z-index: 16;
}
.button {
  position: absolute;
  width: 95px;
  height: 59px;
  top: 125px;
  left: 917px;
  cursor: pointer;
  background: #eeb120;
  border: none;
  z-index: 17;
}
.daftar-nama-jemaat {
  position: absolute;
  width: 616px;
  height: 45px;
  top: 130px;
  left: 100px;
  cursor: pointer;
  color: #ffffff;
  font-family: Kanit, var(--default-font-family);
  font-size: 30px;
  font-weight: 400;
  line-height: 44.85px;
  white-space: nowrap;
  background: transparent;
  border: none;
  z-index: 11;
}
.number {
  display: flex;
  align-items: flex-start;
  justify-content: center;
  position: absolute;
  width: 23px;
  height: 48px;
  top: 130px;
  left: 954px;
  color: #000000;
  font-family: Kanit, var(--default-font-family);
  font-size: 32px;
  font-weight: 400;
  line-height: 47.84px;
  text-align: center;
  white-space: nowrap;
  z-index: 19;
}
.jumlah {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 36px;
  top: 136px;
  left: 830px;
  color: #000000;
  font-family: Kanit, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 35.88px;
  text-align: left;
  white-space: nowrap;
  z-index: 18;
}
.rectangle-4 {
  position: absolute;
  width: 997px;
  height: 82px;
  top: 192px;
  left: 55px;
  background: #ffffff;
  z-index: 5;
}
.rectangle-5 {
  position: absolute;
  width: 997px;
  height: 82px;
  top: 192px;
  left: 55px;
  background: #ffffff;
  z-index: 7;
}
.line-6 {
  position: absolute;
  width: 996px;
  height: 1px;
  top: 192px;
  left: 50%;
  background: url(./assets/images/0dfb8559-1a20-40b8-a35e-b0e813fa7712.png)
    no-repeat center;
  background-size: cover;
  transform: translate(-50%, 0);
  z-index: 4;
}
.rectangle-7 {
  position: absolute;
  width: 997px;
  height: 70px;
  top: 205px;
  left: 55px;
  background: #ffffff;
  z-index: 10;
}
.jackson-wang {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 29px;
  top: 219px;
  left: 99px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 29px;
  text-align: left;
  white-space: nowrap;
  z-index: 12;
}
.rectangle-8 {
  position: absolute;
  width: 997px;
  height: 70px;
  top: 275px;
  left: 55px;
  background: #efefef;
  z-index: 8;
}
.jackson-wang-9 {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 29px;
  top: 293px;
  left: 99px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 29px;
  text-align: left;
  white-space: nowrap;
  z-index: 13;
}
.multimedia {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 45px;
  top: 312px;
  left: 554px;
  color: #ffffff;
  font-family: Kanit, var(--default-font-family);
  font-size: 30px;
  font-weight: 400;
  line-height: 44.85px;
  text-align: left;
  white-space: nowrap;
  z-index: 1;
}
.rectangle-a {
  position: absolute;
  width: 997px;
  height: 70px;
  top: 345px;
  left: 55px;
  background: #ffffff;
  z-index: 6;
}
.jackson-wang-b {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 29px;
  top: 365px;
  left: 100px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 29px;
  text-align: left;
  white-space: nowrap;
  z-index: 14;
}
.rectangle-c {
  position: absolute;
  width: 997px;
  height: 70px;
  top: 415px;
  left: 55px;
  background: #efefef;
  z-index: 3;
}
.jackson-wang-d {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 29px;
  top: 434px;
  left: 100px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 29px;
  text-align: left;
  white-space: nowrap;
  z-index: 15;
} -->

<!-- Add event
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@600&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div class="main-container">
      <div class="rectangle"></div>
      <button class="button-group">
        <div class="group">
          <div class="group-1"><div class="rectangle-2"></div></div>
        </div>
        <div class="ellipse"></div>
        <span class="form-pendaftaran-aktif"
          >Form pendaftaran aktif</span
        ></button
      ><span class="add-event">ADD EVENT</span>
      <div class="rectangle-3"></div>
      <div class="rectangle-4"></div>
      <div class="line"></div>
      <span class="nama-event">Nama event</span>
      <div class="rectangle-5"></div>
      <span class="tempat">Tempat</span>
      <div class="rectangle-6"></div>
      <div class="rectangle-7"></div>
      <div class="line-8"></div>
      <div class="line-9"></div>
      <span class="range-tanggal">Range tanggal</span
      ><span class="waktu-optional">Waktu (optional)</span
      ><span class="apr">APR</span><button class="button"></button>
      <div class="rectangle-a"></div>
      <div class="rectangle-size"></div>
      <span class="april-date">19 April 2024 – 21 April 2024</span
      ><span class="event-description">Deskripsi event</span>
      <div class="rectangle-b"></div>
      <span class="gambar">Gambar</span><button class="rectangle-c"></button
      ><span class="pilih-file">Pilih file</span>
    </div>
    </body>
</html>

:root {
  --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
    "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
    "Source Han Sans CN", sans-serif;
}

.main-container {
  overflow: hidden;
}

.main-container,
.main-container * {
  box-sizing: border-box;
}

input,
select,
textarea,
button {
  outline: 0;
}

.main-container {
  position: relative;
  width: 982px;
  height: 850px;
  margin: 0 auto;
  overflow: hidden auto;
}
.rectangle {
  position: absolute;
  width: 982px;
  height: 850px;
  top: 0;
  left: 0;
  background: #000000;
}
.button-group {
  position: absolute;
  width: 269px;
  height: 49px;
  top: 16px;
  left: 635px;
  cursor: pointer;
  background: transparent;
  border: none;
  z-index: 24;
}
.group {
  position: absolute;
  width: 269px;
  height: 49px;
  top: 0;
  left: 0;
  z-index: 25;
  border-radius: 40px;
}
.group-1 {
  position: absolute;
  width: 269px;
  height: 49px;
  top: 0;
  left: 0;
  z-index: 26;
  border-radius: 40px;
}
.rectangle-2 {
  position: absolute;
  width: 269px;
  height: 49px;
  top: 0;
  left: 0;
  background: #eeb120;
  border: 2px solid #000000;
  z-index: 27;
  border-radius: 40px;
}
.ellipse {
  position: absolute;
  width: 36px;
  height: 36px;
  top: 7px;
  left: 8px;
  background: url(./assets/images/6e9021a0-1964-44c3-ae1b-3d50c36b47a2.png)
    no-repeat center;
  background-size: cover;
  z-index: 28;
  border-radius: 50%;
}
.form-pendaftaran-aktif {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 20px;
  top: 15px;
  left: 50px;
  color: #000000;
  font-family: Inter, var(--default-font-family);
  font-size: 16px;
  font-weight: 600;
  line-height: 20px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: -0.18px;
  z-index: 29;
}
.add-event {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 25px;
  left: 60px;
  color: #ffffff;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 12;
}
.rectangle-3 {
  position: absolute;
  width: 982px;
  height: 769px;
  top: 83px;
  left: 0;
  background: #f1f1f1;
  z-index: 1;
}
.rectangle-4 {
  position: absolute;
  width: 982px;
  height: 769px;
  top: 83px;
  left: 0;
  background: #f1f1f1;
  z-index: 2;
}
.line {
  position: absolute;
  width: 982px;
  height: 1px;
  top: 82px;
  left: 0;
  background: url(./assets/images/e4d8e106-4f38-4a44-bc4d-2f6be15f3f3a.png)
    no-repeat center;
  background-size: cover;
  z-index: 23;
}
.nama-event {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 106px;
  left: 61px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 19;
}
.rectangle-5 {
  position: absolute;
  width: 841px;
  height: 60px;
  top: 157px;
  left: 61px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 14;
}
.tempat {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 235px;
  left: 61px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 20;
}
.rectangle-6 {
  position: absolute;
  width: 403px;
  height: 60px;
  top: 286px;
  left: 61px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 15;
}
.rectangle-7 {
  position: absolute;
  width: 840px;
  height: 60px;
  top: 286px;
  left: 61px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 16;
}
.line-8 {
  position: absolute;
  width: 650.11px;
  height: 10px;
  top: 355px;
  left: 397.896px;
  background: url(./assets/images/d43708ac-3688-4193-9a9c-d1eb350a2690.png)
    no-repeat center;
  background-size: cover;
  z-index: 21;
}
.line-9 {
  position: absolute;
  width: 10.998px;
  height: 50.2px;
  top: 367px;
  left: 398.002px;
  background: url(./assets/images/a3c85ee9-a781-41d9-8b3f-37a0dc691511.png)
    no-repeat center;
  background-size: cover;
  z-index: 7;
}
.range-tanggal {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 369px;
  left: 60px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 22;
}
.waktu-optional {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 371px;
  left: 601px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 9;
}
.apr {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 18.615px;
  top: 409.493px;
  left: -20.631px;
  color: #f4f4f4;
  font-family: Roboto, var(--default-font-family);
  font-size: 16px;
  font-weight: 900;
  line-height: 18.615px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 1.6px;
  z-index: 13;
}
.button {
  position: absolute;
  width: 523px;
  height: 60px;
  top: 417px;
  left: 61px;
  cursor: pointer;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 6;
}
.rectangle-a {
  position: absolute;
  width: 300px;
  height: 60px;
  top: 417px;
  left: 601px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 11;
}
.rectangle-size {
  position: absolute;
  width: 34px;
  height: 34px;
  top: 431px;
  left: 528px;
  background: url(./assets/images/fd556df9-b1cd-44ae-b601-959655842f71.png)
    no-repeat center;
  background-size: cover;
  z-index: 10;
}
.april-date {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 19px;
  top: 437px;
  left: 93px;
  color: #293050;
  font-family: Roboto, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 19px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: -0.18px;
  z-index: 8;
}
.event-description {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 498px;
  left: 60px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 18;
}
.rectangle-b {
  position: absolute;
  width: 841px;
  height: 156px;
  top: 549px;
  left: 60px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 17;
}
.gambar {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 723px;
  left: 61px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 3;
}
.rectangle-c {
  position: absolute;
  width: 169px;
  height: 31px;
  top: 769px;
  left: 61px;
  cursor: pointer;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 4;
  border-radius: 5px;
}
.pilih-file {
  display: flex;
  align-items: flex-start;
  justify-content: center;
  position: absolute;
  width: 159px;
  height: 23px;
  top: 774px;
  left: 66px;
  color: #646464;
  font-family: Roboto, var(--default-font-family);
  font-size: 20px;
  font-weight: 400;
  line-height: 23px;
  text-align: center;
  white-space: nowrap;
  letter-spacing: 0.4px;
  z-index: 5;
}-->

<!-- Edit event
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div class="main-container">
      <div class="rectangle">
        <span class="edit-event">EDIT EVENT </span>
        <div class="rectangle-1">
          <span class="nama-event">Nama event</span>
          <div class="rectangle-2">
            <span class="yess-leardership-mission"
              >YESS Leardership Mission Training VII</span
            >
          </div>
          <span class="tempat">Tempat</span>
          <div class="rectangle-3">
            <div class="rectangle-4"></div>
            <span class="desa-birkium-soe"
              >Desa Birkium, Soe, Nusa Tenggara Timur</span
            >
          </div>
          <div class="flex-row-e">
            <span class="range-tanggal">Range tanggal</span
            ><button class="waktu-optional">Waktu (optional)</button>
            <div class="line"></div>
          </div>
          <div class="flex-row-c">
            <div class="rectangle-5">
              <div class="size"></div>
              <span class="april-date-range">19 April 2024 – 21 April 2024</span
              ><span class="april-date-range-6"
                >19 April 2024 – 21 April 2024</span
              >
            </div>
            <div class="rectangle-7"></div>
          </div>
          <span class="deskripsi-event">Deskripsi event</span>
          <div class="rectangle-8">
            <span class="spiritual-mission"
              >Biarlah semangat misi terus menyala dalam hidup kita.<br />Uis
              Neno nokan kit, Immanuel!<br />Sampe ketemu di YLMT, basodara
              dong!</span
            >
          </div>
          <span class="gambar">Gambar</span>
          <div class="flex-row-cb">
            <button class="rectangle-9">
              <span class="pilih-file">Pilih file</span></button
            ><span class="blablabla-jpg">Blablabla.jpg</span>
          </div>
        </div>
      </div>
      <div class="line-a"></div>
      <div class="line-b"></div>
      <div class="line-c"></div>
      <span class="apr">APR</span>
      <div class="rectangle-d">
        <button class="rectangle-e"><span class="cancel">CANCEL</span></button>
        <div class="button">
          <button class="background"></button>
          <div class="shadow"></div>
          <span class="button-f">SAVE</span>
        </div>
      </div>
    </div>
  </body>
</html>

:root {
  --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
    "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
    "Source Han Sans CN", sans-serif;
}

.main-container {
  overflow: hidden;
}

.main-container,
.main-container * {
  box-sizing: border-box;
}

input,
select,
textarea,
button {
  outline: 0;
}

.main-container {
  position: relative;
  width: 982px;
  height: 919px;
  margin: 0 auto;
  overflow: hidden auto;
}
.rectangle {
  position: absolute;
  width: 982px;
  height: 850px;
  top: 0;
  left: 0;
  font-size: 0px;
  background: #fdfdfd;
}
.edit-event {
  display: block;
  position: relative;
  height: 40px;
  margin: 25px 0 0 60px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 2;
}
.rectangle-1 {
  position: relative;
  width: 982px;
  height: 769px;
  margin: 12px 0 0 0;
  font-size: 0px;
  background: #f1f1f1;
  z-index: 1;
  overflow: visible auto;
}
.nama-event {
  display: block;
  position: relative;
  height: 40px;
  margin: 29px 0 0 61px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 11;
}
.rectangle-2 {
  position: relative;
  width: 841px;
  height: 60px;
  margin: 11px 0 0 61px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 12;
}
.yess-leardership-mission {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 28px;
  top: 16px;
  left: 30px;
  color: #000000;
  font-family: Roboto, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 28px;
  text-align: left;
  white-space: nowrap;
  z-index: 12;
}
.tempat {
  display: block;
  position: relative;
  height: 40px;
  margin: 18px 0 0 61px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 14;
}
.rectangle-3 {
  position: relative;
  width: 840px;
  height: 60px;
  margin: 11px 0 0 61px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 6;
}
.rectangle-4 {
  position: absolute;
  width: 403px;
  height: 60px;
  top: -1px;
  left: -1px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 5;
}
.desa-birkium-soe {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 28px;
  top: 15px;
  left: 30px;
  color: #000000;
  font-family: Roboto, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 28px;
  text-align: left;
  white-space: nowrap;
  z-index: 13;
}
.flex-row-e {
  position: relative;
  width: 797px;
  height: 51.12px;
  margin: 23px 0 0 60px;
  z-index: 32;
}
.range-tanggal {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 40px;
  top: 0;
  left: 0;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 18;
}
.waktu-optional {
  position: absolute;
  width: 257px;
  height: 40px;
  top: 5px;
  left: 540px;
  cursor: pointer;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  white-space: nowrap;
  background: transparent;
  border: none;
  z-index: 19;
}
.line {
  position: absolute;
  width: 10px;
  height: 45.232px;
  top: 5.888px;
  left: 495.25px;
  background: url(./assets/images/b1df8b64-05b7-4e03-a4d0-2554bd33ff36.png)
    no-repeat center;
  background-size: cover;
  z-index: 32;
}
.flex-row-c {
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: relative;
  width: 842px;
  height: 60px;
  margin: -0.12px 0 0 60px;
  z-index: 36;
}
.rectangle-5 {
  flex-shrink: 0;
  position: relative;
  width: 523px;
  height: 60px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 15;
}
.size {
  position: absolute;
  width: 34px;
  height: 34px;
  top: 13px;
  left: 466px;
  background: url(./assets/images/9d787265-fb09-4359-946b-75fa306b102a.png)
    no-repeat center;
  background-size: cover;
  z-index: 29;
}
.april-date-range {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 19px;
  top: 19px;
  left: 31px;
  color: #293050;
  font-family: Roboto, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 19px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: -0.18px;
  z-index: 16;
}
.april-date-range-6 {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  position: absolute;
  height: 19px;
  top: 19px;
  left: 31px;
  color: #293050;
  font-family: Roboto, var(--default-font-family);
  font-size: 24px;
  font-weight: 400;
  line-height: 19px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: -0.18px;
  z-index: 17;
}
.rectangle-7 {
  flex-shrink: 0;
  position: relative;
  width: 297px;
  height: 60px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 36;
}
.deskripsi-event {
  display: block;
  position: relative;
  height: 40px;
  margin: 18px 0 0 60px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 9;
}
.rectangle-8 {
  position: relative;
  width: 842px;
  height: 156px;
  margin: 11px 0 0 60px;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 8;
}
.spiritual-mission {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  width: 572px;
  height: 79px;
  top: 19px;
  left: 31px;
  color: #646464;
  font-family: Roboto, var(--default-font-family);
  font-size: 20px;
  font-weight: 400;
  line-height: 23.438px;
  text-align: left;
  text-overflow: initial;
  letter-spacing: 0.4px;
  z-index: 8;
  overflow: hidden;
}
.gambar {
  display: block;
  position: relative;
  height: 40px;
  margin: 18px 0 0 61px;
  color: #000000;
  font-family: Montserrat, var(--default-font-family);
  font-size: 24px;
  font-weight: 500;
  line-height: 40px;
  text-align: left;
  white-space: nowrap;
  z-index: 10;
}
.flex-row-cb {
  position: relative;
  width: 328px;
  height: 31px;
  margin: 6px 0 0 61px;
  z-index: 34;
}
.rectangle-9 {
  position: absolute;
  width: 169px;
  height: 31px;
  top: 0;
  left: 0;
  cursor: pointer;
  background: #ffffff;
  border: 1px solid #000000;
  z-index: 33;
  border-radius: 5px;
}
.pilih-file {
  display: flex;
  align-items: flex-start;
  justify-content: center;
  position: absolute;
  width: 159px;
  height: 23px;
  top: 4px;
  left: 4px;
  color: #646464;
  font-family: Roboto, var(--default-font-family);
  font-size: 20px;
  font-weight: 400;
  line-height: 23px;
  text-align: center;
  white-space: nowrap;
  letter-spacing: 0.4px;
  z-index: 35;
}
.blablabla-jpg {
  display: flex;
  align-items: flex-start;
  justify-content: center;
  position: absolute;
  width: 159px;
  height: 23px;
  top: 3px;
  left: 169px;
  color: #646464;
  font-family: Roboto, var(--default-font-family);
  font-size: 20px;
  font-weight: 400;
  line-height: 23px;
  text-align: center;
  white-space: nowrap;
  letter-spacing: 0.4px;
  z-index: 34;
}
.line-a {
  position: absolute;
  width: 982px;
  height: 1px;
  top: 82px;
  left: 0;
  background: url(./assets/images/91c8e80e-1d36-426a-bc94-b8d1b4155246.png)
    no-repeat center;
  background-size: cover;
  z-index: 28;
}
.line-b {
  position: absolute;
  width: 169.973px;
  height: 61.548px;
  top: 136.452px;
  left: 866.027px;
  background: url(./assets/images/8aa7c132-91b9-4f2c-b55c-bd4278926825.png)
    no-repeat center;
  background-size: cover;
  z-index: 31;
}
.line-c {
  position: absolute;
  width: 478px;
  height: 10px;
  top: 365px;
  left: 555px;
  background: url(./assets/images/9c4fc9a9-9748-4a4f-83e0-9c465912f8de.png)
    no-repeat center;
  background-size: cover;
  z-index: 30;
}
.apr {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 18.615px;
  top: 409.493px;
  left: -20.631px;
  color: #f4f4f4;
  font-family: Roboto, var(--default-font-family);
  font-size: 16px;
  font-weight: 900;
  line-height: 18.615px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 1.6px;
  z-index: 3;
}
.rectangle-d {
  position: absolute;
  width: 982px;
  height: 99px;
  top: 828px;
  left: 0;
  background: #a1a1a1;
  z-index: 21;
}
.rectangle-e {
  position: absolute;
  width: 143px;
  height: 56px;
  top: 22px;
  left: 616px;
  cursor: pointer;
  background: #e5e5e5;
  border: 1px solid #000000;
  z-index: 26;
}
.cancel {
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  position: absolute;
  height: 24px;
  top: 15px;
  left: 26px;
  color: #000000;
  font-family: DM Sans, var(--default-font-family);
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 1.6px;
  z-index: 27;
}
.button {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: nowrap;
  gap: 8px;
  position: absolute;
  width: 104px;
  height: 56px;
  top: 22px;
  left: 773px;
  padding: 16px 24px 16px 24px;
  z-index: 22;
  border-radius: 40px;
}
.background {
  flex-shrink: 0;
  position: absolute;
  width: 134px;
  height: 56px;
  top: 50%;
  left: 50%;
  cursor: pointer;
  background: #000000;
  border: none;
  transform: translate(-50%, -50%);
  z-index: 24;
}
.shadow {
  flex-shrink: 0;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: #000000;
  z-index: 23;
}
.button-f {
  flex-shrink: 0;
  flex-basis: auto;
  position: relative;
  height: 24px;
  color: #ffffff;
  font-family: DM Sans, var(--default-font-family);
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: left;
  white-space: nowrap;
  letter-spacing: 2px;
  z-index: 25;
} -->